eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: zuul-server
zuul:
  routes:
    say-hello:
      path: /say-hello-service/**
      serviceId: say-hello-service
    greeting:
      path: /greeting-service/**
      serviceId: greeting-service